baseURL = 'https://makvit9.github.io'
languageCode = 'en-us'
title = 'Makvit 9'
theme = 'hugo-coder'

[pagination]
pagerSize = 6

[params]
author= "Majed Alhadeed"
description = "Welcome to my personal website"
keywords = "developer,personal"
# Dark / Light modes
colorScheme = "auto"

hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon ="fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Makvit9"

[[languages.en.menu.main]]
name = "About"
weight = 1 
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "/posts"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
